version: '3.9'
services:
  nginx-dev:
    image: "${DOCKER_HUB_NICKNAME}/${DOCKER_REGISTRY_REPO_NAME}:${COMPOSE_PROJECT_NAME}-nginx-dev"
    restart: unless-stopped
    depends_on:
      - backend-dev
      # - frontend-dev
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      target: dev_nginx
      args:
        - NGINX_HTTP_PORT=${NGINX_HTTP_PORT}
    environment:
      - TZ=${TZ}
      - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
      - INNER_DEV_FRONT_LIVE_RELOAD_SERVER_PORT=${INNER_DEV_FRONT_LIVE_RELOAD_SERVER_PORT}
      - INNER_BACKEND_HTTP_SERVER_PORT=${INNER_BACKEND_HTTP_SERVER_PORT}
      - INNER_BACKEND_WS_SERVER_PORT=${INNER_BACKEND_WS_SERVER_PORT}
    ports:
      - ${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}/tcp
    networks:
      nginx-front-net-dev:
      nginx-back-net-dev:

  backend-dev:
    image: "${DOCKER_HUB_NICKNAME}/${DOCKER_REGISTRY_REPO_NAME}:${COMPOSE_PROJECT_NAME}-backend-dev"
    restart: unless-stopped
    depends_on:
      - postgres-dev
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      target: development
      args:
        - INNER_BACKEND_HTTP_SERVER_PORT=${INNER_BACKEND_HTTP_SERVER_PORT}
        - INNER_BACKEND_WS_SERVER_PORT=${INNER_BACKEND_WS_SERVER_PORT}
    environment:
      - TZ=${TZ}
      - PY_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - USER_PASSWORD_HASH_SALT=${USER_PASSWORD_HASH_SALT}

      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}

      - SERVER_PORT=${INNER_BACKEND_HTTP_SERVER_PORT}
      - WEB_SOCKET_SERVER_PORT=${INNER_BACKEND_WS_SERVER_PORT}
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
        consistency: delegated
    ports:
      - ${DEV_BACKEND_DEBUGGER_PORT}:${DEV_BACKEND_DEBUGGER_PORT}
    networks:
      nginx-back-net-dev:
      back-db-net-dev:

  postgres-dev:
    image: postgres
    restart: unless-stopped
    command: "-c default_text_search_config=pg_catalog.russian"
    environment:
      - TZ=${TZ}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    # In standard dockerfile of postgres there is special instruction that assigns a volume to /var/lib/postgresql/data
    # I want to get fresh database every time I restart it.
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT_EXPOSED_TO_DEV_LOCALHOST}:${DATABASE_PORT}
    networks:
      back-db-net-dev:
      pgcli-db-net-dev:

  pgcli-dev:
    image: daxart/pgcli:latest
    profiles:
      - use_pgcli
    command:
      - postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME}
    networks:
      pgcli-db-net-dev:


networks:
  nginx-front-net-dev: {}
  nginx-back-net-dev: {}

  back-db-net-dev: {}
  pgcli-db-net-dev: {}
